[project]
name = "gptlike"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dataset>=1.6.2",
    "matplotlib>=3.10.0",
    "tiktoken>=0.8.0",
    "torch>=2.6.0",
    "transformers>=4.48.2",
]
